# Numpy Assignment


Q-1. Write a function so that the columns of the output matrix are powers of the input
vector.
<br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import pandas as pd
import numpy as np

In [2]:
def vander1(arr,N):
    a=[]
    for i in range(N):
        for j in arr:
            a.append(j**(N - i -1))
    ab=np.array(a).reshape(3,4).T
    return ab

In [5]:
arr=np.array([1,2,3,4])

result1=vander1(arr,3)
result1

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [6]:
#Another way:

def vander2(arr,N):
    return np.column_stack([arr**(N-1-i) for i in range(N)])


In [9]:
x=np.array([1,2,3,4,5])
N=4
result2=vander2(x,N)
result2

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]], dtype=int32)

Q-2. Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [10]:
def mov_avg(arr,window):
    ss=[]
    for i in range(len(arr)-window+1):
        summ=0
        for j in range(w):
            summ+=arr[i+j]
        ss.append(summ/window)
    return ss
    

    

In [11]:
arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
w=3
np.array(mov_avg(arr,w)).round(3)

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])